[build]
builder = "nixpacks"
buildCommand = "corepack pnpm install --frozen-lockfile --filter iln-indexer... && corepack pnpm --filter iln-indexer build"

[deploy]
startCommand = "corepack pnpm --filter iln-indexer start"
numReplicas = 1
healthcheckPath = "/v1/health"
healthcheckTimeout = 120
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
