name: PR title lint

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  lint:
    runs-on: namespace-profile-nursca
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: pnpm/action-setup@v4
        with:
          version: "9.0.0"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts
      - name: Lint PR title
        run: |
          echo "${{ github.event.pull_request.title }}" > pr_title
          pnpm exec commitlint --config commitlint.config.js --edit pr_title
